arrGl = [
    {'idGl': 'VN', 'nameGl': 'Vietnam'},
    {'idGl': 'US', 'nameGl': 'United States'},
    {'idGl': 'GB', 'nameGl': 'United Kingdom'},
    {'idGl': 'AU', 'nameGl': 'Australia'},
    {'idGl': 'SG', 'nameGl': 'Singapore'},
    {'idGl': 'ID', 'nameGl': 'Indonesia'},
    {'idGl': 'A1', 'nameGl': 'Anonymous Proxy'},
    {'idGl': 'A2', 'nameGl': 'Satellite Provider'},
    {'idGl': 'O1', 'nameGl': 'Other Country'},
    {'idGl': 'AD', 'nameGl': 'Andorra'},
    {'idGl': 'AE', 'nameGl': 'United Arab Emirates'},
    {'idGl': 'AF', 'nameGl': 'Afghanistan'},
    {'idGl': 'AG', 'nameGl': 'Antigua and Barbuda'},
    {'idGl': 'AI', 'nameGl': 'Anguilla'},
    {'idGl': 'AL', 'nameGl': 'Albania'},
    {'idGl': 'AM', 'nameGl': 'Armenia'},
    {'idGl': 'AO', 'nameGl': 'Angola'},
    {'idGl': 'AP', 'nameGl': 'Asia/Pacific Region'},
    {'idGl': 'AQ', 'nameGl': 'Antarctica'},
    {'idGl': 'AR', 'nameGl': 'Argentina'},
    {'idGl': 'AS', 'nameGl': 'American Samoa'},
    {'idGl': 'AT', 'nameGl': 'Austria'},
    {'idGl': 'AW', 'nameGl': 'Aruba'},
    {'idGl': 'AX', 'nameGl': 'Aland Islands'},
    {'idGl': 'AZ', 'nameGl': 'Azerbaijan'},
    {'idGl': 'BA', 'nameGl': 'Bosnia and Herzegovina'},
    {'idGl': 'BB', 'nameGl': 'Barbados'},
    {'idGl': 'BD', 'nameGl': 'Bangladesh'},
    {'idGl': 'BE', 'nameGl': 'Belgium'},
    {'idGl': 'BF', 'nameGl': 'Burkina Faso'},
    {'idGl': 'BG', 'nameGl': 'Bulgaria'},
    {'idGl': 'BH', 'nameGl': 'Bahrain'},
    {'idGl': 'BI', 'nameGl': 'Burundi'},
    {'idGl': 'BJ', 'nameGl': 'Benin'},
    {'idGl': 'BL', 'nameGl': 'Saint Bartelemey'},
    {'idGl': 'BM', 'nameGl': 'Bermuda'},
    {'idGl': 'BN', 'nameGl': 'Brunei Darussalam'},
    {'idGl': 'BO', 'nameGl': 'Bolivia'},
    {'idGl': 'BQ', 'nameGl': 'Bonaire Saint Eustatius and Saba'},
    {'idGl': 'BR', 'nameGl': 'Brazil'},
    {'idGl': 'BS', 'nameGl': 'Bahamas'},
    {'idGl': 'BT', 'nameGl': 'Bhutan'},
    {'idGl': 'BV', 'nameGl': 'Bouvet Island'},
    {'idGl': 'BW', 'nameGl': 'Botswana'},
    {'idGl': 'BY', 'nameGl': 'Belarus'},
    {'idGl': 'BZ', 'nameGl': 'Belize'},
    {'idGl': 'CA', 'nameGl': 'Canada'},
    {'idGl': 'CC', 'nameGl': 'Cocos (Keeling) Islands'},
    {'idGl': 'CD', 'nameGl': 'Congo The Democratic Republic of the'},
    {'idGl': 'CF', 'nameGl': 'Central African Republic'},
    {'idGl': 'CG', 'nameGl': 'Congo'},
    {'idGl': 'CH', 'nameGl': 'Switzerland'},
    {'idGl': 'CI', 'nameGl': 'Cote d Ivoire'},
    {'idGl': 'CK', 'nameGl': 'Cook Islands'},
    {'idGl': 'CL', 'nameGl': 'Chile'},
    {'idGl': 'CM', 'nameGl': 'Cameroon'},
    {'idGl': 'CN', 'nameGl': 'China'},
    {'idGl': 'CO', 'nameGl': 'Colombia'},
    {'idGl': 'CR', 'nameGl': 'Costa Rica'},
    {'idGl': 'CU', 'nameGl': 'Cuba'},
    {'idGl': 'CV', 'nameGl': 'Cape Verde'},
    {'idGl': 'CW', 'nameGl': 'Curacao'},
    {'idGl': 'CX', 'nameGl': 'Christmas Island'},
    {'idGl': 'CY', 'nameGl': 'Cyprus'},
    {'idGl': 'CZ', 'nameGl': 'Czech Republic'},
    {'idGl': 'DE', 'nameGl': 'Germany'},
    {'idGl': 'DJ', 'nameGl': 'Djibouti'},
    {'idGl': 'DK', 'nameGl': 'Denmark'},
    {'idGl': 'DM', 'nameGl': 'Dominica'},
    {'idGl': 'DO', 'nameGl': 'Dominican Republic'},
    {'idGl': 'DZ', 'nameGl': 'Algeria'},
    {'idGl': 'EC', 'nameGl': 'Ecuador'},
    {'idGl': 'EE', 'nameGl': 'Estonia'},
    {'idGl': 'EG', 'nameGl': 'Egypt'},
    {'idGl': 'EH', 'nameGl': 'Western Sahara'},
    {'idGl': 'ER', 'nameGl': 'Eritrea'},
    {'idGl': 'ES', 'nameGl': 'Spain'},
    {'idGl': 'ET', 'nameGl': 'Ethiopia'},
    {'idGl': 'EU', 'nameGl': 'Europe'},
    {'idGl': 'FI', 'nameGl': 'Finland'},
    {'idGl': 'FJ', 'nameGl': 'Fiji'},
    {'idGl': 'FK', 'nameGl': 'Falkland Islands (Malvinas)'},
    {'idGl': 'FM', 'nameGl': 'Micronesia Federated States of'},
    {'idGl': 'FO', 'nameGl': 'Faroe Islands'},
    {'idGl': 'FR', 'nameGl': 'France'},
    {'idGl': 'GA', 'nameGl': 'Gabon'},

    {'idGl': 'GD', 'nameGl': 'Grenada'},
    {'idGl': 'GE', 'nameGl': 'Georgia'},
    {'idGl': 'GF', 'nameGl': 'French Guiana'},
    {'idGl': 'GG', 'nameGl': 'Guernsey'},
    {'idGl': 'GH', 'nameGl': 'Ghana'},
    {'idGl': 'GI', 'nameGl': 'Gibraltar'},
    {'idGl': 'GL', 'nameGl': 'Greenland'},
    {'idGl': 'GM', 'nameGl': 'Gambia'},
    {'idGl': 'GN', 'nameGl': 'Guinea'},
    {'idGl': 'GP', 'nameGl': 'Guadeloupe'},
    {'idGl': 'GQ', 'nameGl': 'Equatorial Guinea'},
    {'idGl': 'GR', 'nameGl': 'Greece'},
    {'idGl': 'GS', 'nameGl': 'South Georgia and the South Sandwich Islands'},
    {'idGl': 'GT', 'nameGl': 'Guatemala'},
    {'idGl': 'GU', 'nameGl': 'Guam'},
    {'idGl': 'GW', 'nameGl': 'Guinea-Bissau'},
    {'idGl': 'GY', 'nameGl': 'Guyana'},
    {'idGl': 'HK', 'nameGl': 'Hong Kong'},
    {'idGl': 'HM', 'nameGl': 'Heard Island and McDonald Islands'},
    {'idGl': 'HN', 'nameGl': 'Honduras'},
    {'idGl': 'HR', 'nameGl': 'Croatia'},
    {'idGl': 'HT', 'nameGl': 'Haiti'},
    {'idGl': 'HU', 'nameGl': 'Hungary'},

    {'idGl': 'IE', 'nameGl': 'Ireland'},
    {'idGl': 'IL', 'nameGl': 'Israel'},
    {'idGl': 'IM', 'nameGl': 'Isle of Man'},
    {'idGl': 'IN', 'nameGl': 'India'},
    {'idGl': 'IO', 'nameGl': 'British Indian Ocean Territory'},
    {'idGl': 'IQ', 'nameGl': 'Iraq'},
    {'idGl': 'IR', 'nameGl': 'Iran Islamic Republic of'},
    {'idGl': 'IS', 'nameGl': 'Iceland'},
    {'idGl': 'IT', 'nameGl': 'Italy'},
    {'idGl': 'JE', 'nameGl': 'Jersey'},
    {'idGl': 'JM', 'nameGl': 'Jamaica'},
    {'idGl': 'JO', 'nameGl': 'Jordan'},
    {'idGl': 'JP', 'nameGl': 'Japan'},
    {'idGl': 'KE', 'nameGl': 'Kenya'},
    {'idGl': 'KG', 'nameGl': 'Kyrgyzstan'},
    {'idGl': 'KH', 'nameGl': 'Cambodia'},
    {'idGl': 'KI', 'nameGl': 'Kiribati'},
    {'idGl': 'KM', 'nameGl': 'Comoros'},
    {'idGl': 'KN', 'nameGl': 'Saint Kitts and Nevis'},
    {'idGl': 'KP', 'nameGl': 'Korea Democratic Peoples Republic of'},
    {'idGl': 'KR', 'nameGl': 'Korea Republic of'},
    {'idGl': 'KW', 'nameGl': 'Kuwait'},
    {'idGl': 'KY', 'nameGl': 'Cayman Islands'},
    {'idGl': 'KZ', 'nameGl': 'Kazakhstan'},
    {'idGl': 'LA', 'nameGl': 'Lao Peoples Democratic Republic'},
    {'idGl': 'LB', 'nameGl': 'Lebanon'},
    {'idGl': 'LC', 'nameGl': 'Saint Lucia'},
    {'idGl': 'LI', 'nameGl': 'Liechtenstein'},
    {'idGl': 'LK', 'nameGl': 'Sri Lanka'},
    {'idGl': 'LR', 'nameGl': 'Liberia'},
    {'idGl': 'LS', 'nameGl': 'Lesotho'},
    {'idGl': 'LT', 'nameGl': 'Lithuania'},
    {'idGl': 'LU', 'nameGl': 'Luxembourg'},
    {'idGl': 'LV', 'nameGl': 'Latvia'},
    {'idGl': 'LY', 'nameGl': 'Libyan Arab Jamahiriya'},
    {'idGl': 'MA', 'nameGl': 'Morocco'},
    {'idGl': 'MC', 'nameGl': 'Monaco'},
    {'idGl': 'MD', 'nameGl': 'Moldova Republic of'},
    {'idGl': 'ME', 'nameGl': 'Montenegro'},
    {'idGl': 'MF', 'nameGl': 'Saint Martin'},
    {'idGl': 'MG', 'nameGl': 'Madagascar'},
    {'idGl': 'MH', 'nameGl': 'Marshall Islands'},
    {'idGl': 'MK', 'nameGl': 'Macedonia'},
    {'idGl': 'ML', 'nameGl': 'Mali'},
    {'idGl': 'MM', 'nameGl': 'Myanmar'},
    {'idGl': 'MN', 'nameGl': 'Mongolia'},
    {'idGl': 'MO', 'nameGl': 'Macao'},
    {'idGl': 'MP', 'nameGl': 'Northern Mariana Islands'},
    {'idGl': 'MQ', 'nameGl': 'Martinique'},
    {'idGl': 'MR', 'nameGl': 'Mauritania'},
    {'idGl': 'MS', 'nameGl': 'Montserrat'},
    {'idGl': 'MT', 'nameGl': 'Malta'},
    {'idGl': 'MU', 'nameGl': 'Mauritius'},
    {'idGl': 'MV', 'nameGl': 'Maldives'},
    {'idGl': 'MW', 'nameGl': 'Malawi'},
    {'idGl': 'MX', 'nameGl': 'Mexico'},
    {'idGl': 'MY', 'nameGl': 'Malaysia'},
    {'idGl': 'MZ', 'nameGl': 'Mozambique'},
    {'idGl': 'NA', 'nameGl': 'Namibia'},
    {'idGl': 'NC', 'nameGl': 'New Caledonia'},
    {'idGl': 'NE', 'nameGl': 'Niger'},
    {'idGl': 'NF', 'nameGl': 'Norfolk Island'},
    {'idGl': 'NG', 'nameGl': 'Nigeria'},
    {'idGl': 'NI', 'nameGl': 'Nicaragua'},
    {'idGl': 'NL', 'nameGl': 'Netherlands'},
    {'idGl': 'NO', 'nameGl': 'Norway'},
    {'idGl': 'NP', 'nameGl': 'Nepal'},
    {'idGl': 'NR', 'nameGl': 'Nauru'},
    {'idGl': 'NU', 'nameGl': 'Niue'},
    {'idGl': 'NZ', 'nameGl': 'New Zealand'},
    {'idGl': 'OM', 'nameGl': 'Oman'},
    {'idGl': 'PA', 'nameGl': 'Panama'},
    {'idGl': 'PE', 'nameGl': 'Peru'},
    {'idGl': 'PF', 'nameGl': 'French Polynesia'},
    {'idGl': 'PG', 'nameGl': 'Papua New Guinea'},
    {'idGl': 'PH', 'nameGl': 'Philippines'},
    {'idGl': 'PK', 'nameGl': 'Pakistan'},
    {'idGl': 'PL', 'nameGl': 'Poland'},
    {'idGl': 'PM', 'nameGl': 'Saint Pierre and Miquelon'},
    {'idGl': 'PN', 'nameGl': 'Pitcairn'},
    {'idGl': 'PR', 'nameGl': 'Puerto Rico'},
    {'idGl': 'PS', 'nameGl': 'Palestinian Territory'},
    {'idGl': 'PT', 'nameGl': 'Portugal'},
    {'idGl': 'PW', 'nameGl': 'Palau'},
    {'idGl': 'PY', 'nameGl': 'Paraguay'},
    {'idGl': 'QA', 'nameGl': 'Qatar'},
    {'idGl': 'RE', 'nameGl': 'Reunion'},
    {'idGl': 'RO', 'nameGl': 'Romania'},
    {'idGl': 'RS', 'nameGl': 'Serbia'},
    {'idGl': 'RU', 'nameGl': 'Russian Federation'},
    {'idGl': 'RW', 'nameGl': 'Rwanda'},
    {'idGl': 'SA', 'nameGl': 'Saudi Arabia'},
    {'idGl': 'SB', 'nameGl': 'Solomon Islands'},
    {'idGl': 'SC', 'nameGl': 'Seychelles'},
    {'idGl': 'SD', 'nameGl': 'Sudan'},
    {'idGl': 'SE', 'nameGl': 'Sweden'},

    {'idGl': 'SH', 'nameGl': 'Saint Helena'},
    {'idGl': 'SI', 'nameGl': 'Slovenia'},
    {'idGl': 'SJ', 'nameGl': 'Svalbard and Jan Mayen'},
    {'idGl': 'SK', 'nameGl': 'Slovakia'},
    {'idGl': 'SL', 'nameGl': 'Sierra Leone'},
    {'idGl': 'SM', 'nameGl': 'San Marino'},
    {'idGl': 'SN', 'nameGl': 'Senegal'},
    {'idGl': 'SO', 'nameGl': 'Somalia'},
    {'idGl': 'SR', 'nameGl': 'Suriname'},
    {'idGl': 'SS', 'nameGl': 'South Sudan'},
    {'idGl': 'ST', 'nameGl': 'Sao Tome and Principe'},
    {'idGl': 'SV', 'nameGl': 'El Salvador'},
    {'idGl': 'SX', 'nameGl': 'Sint Maarten'},
    {'idGl': 'SY', 'nameGl': 'Syrian Arab Republic'},
    {'idGl': 'SZ', 'nameGl': 'Swaziland'},
    {'idGl': 'TC', 'nameGl': 'Turks and Caicos Islands'},
    {'idGl': 'TD', 'nameGl': 'Chad'},
    {'idGl': 'TF', 'nameGl': 'French Southern Territories'},
    {'idGl': 'TG', 'nameGl': 'Togo'},
    {'idGl': 'TH', 'nameGl': 'Thailand'},
    {'idGl': 'TJ', 'nameGl': 'Tajikistan'},
    {'idGl': 'TK', 'nameGl': 'Tokelau'},
    {'idGl': 'TL', 'nameGl': 'Timor-Leste'},
    {'idGl': 'TM', 'nameGl': 'Turkmenistan'},
    {'idGl': 'TN', 'nameGl': 'Tunisia'},
    {'idGl': 'TO', 'nameGl': 'Tonga'},
    {'idGl': 'TR', 'nameGl': 'Turkey'},
    {'idGl': 'TT', 'nameGl': 'Trinidad and Tobago'},
    {'idGl': 'TV', 'nameGl': 'Tuvalu'},
    {'idGl': 'TW', 'nameGl': 'Taiwan'},
    {'idGl': 'TZ', 'nameGl': 'Tanzania United Republic of'},
    {'idGl': 'UA', 'nameGl': 'Ukraine'},
    {'idGl': 'UG', 'nameGl': 'Uganda'},
    {'idGl': 'UM', 'nameGl': 'United States Minor Outlying Islands'},

    {'idGl': 'UY', 'nameGl': 'Uruguay'},
    {'idGl': 'UZ', 'nameGl': 'Uzbekistan'},
    {'idGl': 'VA', 'nameGl': 'Holy See (Vatican City State)'},
    {'idGl': 'VC', 'nameGl': 'Saint Vincent and the Grenadines'},
    {'idGl': 'VE', 'nameGl': 'Venezuela'},
    {'idGl': 'VG', 'nameGl': 'Virgin Islands British'},
    {'idGl': 'VI', 'nameGl': 'Virgin Islands U.S.'},
    {'idGl': 'VU', 'nameGl': 'Vanuatu'},
    {'idGl': 'WF', 'nameGl': 'Wallis and Futuna'},
    {'idGl': 'WS', 'nameGl': 'Samoa'},
    {'idGl': 'YE', 'nameGl': 'Yemen'},
    {'idGl': 'YT', 'nameGl': 'Mayotte'},
    {'idGl': 'ZA', 'nameGl': 'South Africa'},
    {'idGl': 'ZM', 'nameGl': 'Zambia'},
    {'idGl': 'ZW', 'nameGl': 'Zimbabwe'}
]
module.exports = arrGl